services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llave-web-dev
    ports:
      - "4321:4321"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PUBLIC_SUPABASE_URL: "${PUBLIC_SUPABASE_URL}"
      PUBLIC_SUPABASE_ANON_KEY: "${PUBLIC_SUPABASE_ANON_KEY}"
      PUBLIC_BRAND_COLOR: "${PUBLIC_BRAND_COLOR:-#E2905C}"
      PUBLIC_BRAND_NAME: "${PUBLIC_BRAND_NAME:-LLAVE}"
      PUBLIC_ALLOWED_GOOGLE_DOMAIN: "${PUBLIC_ALLOWED_GOOGLE_DOMAIN:-tu-dominio.com}"
    volumes:
      - .:/app
      - /app/node_modules
